/*INICIANDO UMA TRANSAÇÃO E VOLTANDO ATRAS*/
START TRANSACTION;
SELECT * FROM VENDEDORES;
UPDATE vendedores SET COMISSAO = COMISSAO *1.35;
SELECT*FROM vendedores;
ROLLBACK;

SELECT * FROM VENDEDORES;

/* CONFIRMANDO UMA TRANSAÇÃO*/
START TRANSACTION;
SELECT * FROM VENDEDORES;
UPDATE vendedores SET COMISSAO = COMISSAO *1.35;
SELECT*FROM vendedores;
COMMIT;
SELECT * FROM VENDEDORES;