SELECT * FROM produtos;

UPDATE PRODUTOS SET PRECO_LISTA = 5.00
WHERE CODIGO ='1000889';
SELECT * FROM produtos;

/*MODIFICANDO MAIS DE UM CAMPO*/
UPDATE PRODUTOS SET EMBALAGEM = 'PET',
TAMANHO='1 LITRO', DESCRITOR='SABOR DA MONTANHA - 1 LITRO - UVA'
WHERE CODIGO ='1000889';
SELECT * FROM produtos;

/* MODIFICANDO EM LOTE*/
UPDATE produtos SET PRECO_LISTA = PRECO_LISTA * 1.1
WHERE SABOR ='MARACUJA';
SELECT * FROM PRODUTOS WHERE SABOR ='MARACUJA';