
/* VISUALIZANDO AS INFORMAÇÕES*/
USE VENDAS_SUCOS;
SELECT * FROM SUCOS_VENDAS.TABELA_DE_PRODUTOS;
SELECT CODIGO_DO_PRODUTO AS CODIGO , NOME_DO_PRODUTO AS DESCRITOS,
EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA AS PRECO_LISTA
FROM SUCOS_VENDAS.TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM PRODUTOS);

/* IMPORTANDO INFORMAÇÕES DE UMA TABELA PARA OUTRA*/
INSERT INTO PRODUTOS
SELECT CODIGO_DO_PRODUTO AS CODIGO , NOME_DO_PRODUTO AS DESCRITOS,
SABOR,TAMANHO,EMBALAGEM,PRECO_DE_LISTA AS PRECO_LISTA
FROM SUCOS_VENDAS.TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM PRODUTOS);

SELECT * FROM produtos;