SELECT YEAR(DATA_VENDA), SUM(QUANTIDADE*PRECO*IMPOSTO) AS FATURAMENTO
	FROM notas_fiscais A 
	INNER JOIN itens_notas_fiscais B
	ON A.NUMERO = B.NUMERO
GROUP BY YEAR(DATA_VENDA);


SELECT YEAR(DATA_VENDA),
    SUM(QUANTIDADE * PRECO * IMPOSTO) AS FATURAMENTO
    FROM notas_fiscais NF
    INNER JOIN itens_notas_fiscais INF
    ON NF.NUMERO = INF. NUMERO 
GROUP BY YEAR(DATA_VENDA);